fix errors

diff --git a/.github/workflows/go-lint-build.yml b/.github/workflows/go-lint-build.yml
--- a/.github/workflows/go-lint-build.yml
+++ b/.github/workflows/go-lint-build.yml
@@ -12,6 +12,50 @@ permissions:
   pull-requests: read
 
 jobs:
+  gofmt-unix:
+    strategy:
+      matrix:
+        go: ["1.20"]
+        os: [macos-latest, ubuntu-latest]
+    name: gofmt
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version: ${{ matrix.go }}
+          cache: true
+      - name: Run format checks
+        run: |
+          if [ $(gofmt -d -l -e . | wc -l) -eq 0 ]; then
+              printf 'Format Checks Have Passed!!!'
+          else
+              printf 'Format Checks Have Failed!\nPlease use gofmt in your system to format your code.'
+              gofmt -l -e -d . 
+              exit 1 
+          fi
+  gofmt-windows:
+    strategy:
+      matrix:
+        go: ["1.20"]
+        os: [windows-latest]
+    name: gofmt
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-go@v4
+        with:
+          go-version: ${{ matrix.go }}
+          cache: true
+      - name: Run format checks
+        run: |
+          if ((gofmt -d -l -e . | Measure-Object -Line).Lines -eq 0) {
+            Write-Host 'Format Checks Have Passed!!!'
+          } else {
+            Write-Host 'Format Checks Have Failed!'
+            gofmt -l -e -d .
+            exit 1
+          }
   golangci:
     strategy:
       matrix:
@@ -44,23 +88,3 @@ jobs:
 
       - name: Run staticcheck
         run: staticcheck ./...
-
-      - name: Run format checks
-        run: |
-          if ["${{ matrix.os }}" == "windows-latest"]; then
-            if ((gofmt -d -l -e . | Measure-Object -Line).Lines -eq 0) {
-              Write-Host 'Format Checks Have Passed!!!'
-            } else {
-              Write-Host 'Format Checks Have Failed!'
-              gofmt -l -e -d .
-              exit 1
-            }
-          else
-            if [ $(gofmt -d -l -e . | wc -l) -eq 0 ]; then
-              printf 'Format Checks Have Passed!!!'
-            else
-              printf 'Format Checks Have Failed!\nPlease use gofmt in your system to format your code.'
-              gofmt -l -e -d . 
-              exit 1 
-            fi
-          fi
